### ISSUE TITLE
hiding year

### ISSUE THREAD

**Issue by rodic** [jmauzy/react-bootstrap-datetimepicker-noicon#1]
is there an option to hide year? i'm only interested in day and month and showing year in toolbar is confusing.

**Comment by jmauzy** [comment]
Because the picker parses its output to moment.js, it's necessary for the year to be present. 

It would be possible to allow a default year to be passed in as a prop and the year picker then hidden/disabled, but even with that workaround the output from the form is still a moment object, not just a day and month. Are regular selects are better for your use case?

**Comment by rodic** [comment]
thanks jmauzy. client wants picker like this one so i made a dirty hack to hide year and will use customized version, but your idea with default year sounds great. think that moment object with default year wouldn't be a problem for anyone who care only for day and month, but i imagine it wouldn't be very common usecase.
